In [ ]:
import pandas as pd

df = pd.read_parquet("hf://datasets/ButterChicken98/plantvillage-image-text-pairs/data/train-00000-of-00001.parquet")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
df

,image,caption,captions
0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato healthy,[A vibrant green and healthy tomato leaf with ...
1,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato Late blight,[A tomato leaf showing dark brown lesions and ...
2,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato healthy,[A vibrant green and healthy tomato leaf with ...
3,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato mosaic virus,[A tomato leaf with mosaic-like patterns of li...
4,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Pepper bell healthy,"[A fresh green bell pepper leaf with a smooth,..."
...,...,...,...
20633,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Potato Early blight,[A potato leaf with concentric brown rings for...
20634,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato Spider mites Two spotted spider mite,[A tomato leaf infested with two-spotted spide...
20635,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Potato Late blight,"[A potato leaf showing dark, water-soaked lesi..."
20636,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato Spider mites Two spotted spider mite,[A tomato leaf infested with two-spotted spide...
20637,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,Tomato Septoria leaf spot,"[A tomato leaf showing small, circular brown s..."

In [ ]:
df = df.drop(columns= ["image"])
df

,caption,captions
0,Tomato healthy,[A vibrant green and healthy tomato leaf with ...
1,Tomato Late blight,[A tomato leaf showing dark brown lesions and ...
2,Tomato healthy,[A vibrant green and healthy tomato leaf with ...
3,Tomato mosaic virus,[A tomato leaf with mosaic-like patterns of li...
4,Pepper bell healthy,"[A fresh green bell pepper leaf with a smooth,..."
...,...,...
20633,Potato Early blight,[A potato leaf with concentric brown rings for...
20634,Tomato Spider mites Two spotted spider mite,[A tomato leaf infested with two-spotted spide...
20635,Potato Late blight,"[A potato leaf showing dark, water-soaked lesi..."
20636,Tomato Spider mites Two spotted spider mite,[A tomato leaf infested with two-spotted spide...
20637,Tomato Septoria leaf spot,"[A tomato leaf showing small, circular brown s..."

In [ ]:
df = df.explode("captions")
df

,caption,captions
0,Tomato healthy,A vibrant green and healthy tomato leaf with s...
0,Tomato healthy,"A healthy Solanum lycopersicum leaf, free of d..."
0,Tomato healthy,"A fresh tomato leaf outdoors, glowing in sunli..."
0,Tomato healthy,"A clean and healthy tomato leaf image, perfect..."
1,Tomato Late blight,A tomato leaf showing dark brown lesions and w...
...,...,...
20636,Tomato Spider mites Two spotted spider mite,An image of a tomato leaf displaying symptoms ...
20637,Tomato Septoria leaf spot,"A tomato leaf showing small, circular brown sp..."
20637,Tomato Septoria leaf spot,A tomato plant leaf infected with Septoria lyc...
20637,Tomato Septoria leaf spot,A tomato leaf outdoors with visible signs of S...
20637,Tomato Septoria leaf spot,A dataset image of a tomato leaf showing sympt...

In [ ]:
df["caption"].unique().tolist()

['Tomato healthy',
 'Tomato Late blight',
 'Tomato mosaic virus',
 'Pepper bell healthy',
 'Potato Early blight',
 'Tomato Early blight',
 'Tomato YellowLeaf Curl Virus',
 'Tomato Target Spot',
 'Pepper bell Bacterial spot',
 'Tomato Septoria leaf spot',
 'Tomato Spider mites Two spotted spider mite',
 'Tomato Bacterial spot',
 'Potato Late blight',
 'Tomato Leaf Mold',
 'Potato healthy']

In [ ]:
df.to_csv("dataset.csv")

In [ ]:
df = pd.read_csv("dataset.csv")
df

,Unnamed: 0,caption,captions
0,0,Tomato healthy,A vibrant green and healthy tomato leaf with s...
1,0,Tomato healthy,"A healthy Solanum lycopersicum leaf, free of d..."
2,0,Tomato healthy,"A fresh tomato leaf outdoors, glowing in sunli..."
3,0,Tomato healthy,"A clean and healthy tomato leaf image, perfect..."
4,1,Tomato Late blight,A tomato leaf showing dark brown lesions and w...
...,...,...,...
82547,20636,Tomato Spider mites Two spotted spider mite,An image of a tomato leaf displaying symptoms ...
82548,20637,Tomato Septoria leaf spot,"A tomato leaf showing small, circular brown sp..."
82549,20637,Tomato Septoria leaf spot,A tomato plant leaf infected with Septoria lyc...
82550,20637,Tomato Septoria leaf spot,A tomato leaf outdoors with visible signs of S...
82551,20637,Tomato Septoria leaf spot,A dataset image of a tomato leaf showing sympt...

In [ ]:
df = df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"], errors="ignore")

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
encoder = LabelEncoder()
encoder.fit(df["caption"].tolist())
df["label"] = encoder.transform(df["caption"].tolist())
df

,caption,captions,label
0,Tomato healthy,A vibrant green and healthy tomato leaf with s...,13
1,Tomato healthy,"A healthy Solanum lycopersicum leaf, free of d...",13
2,Tomato healthy,"A fresh tomato leaf outdoors, glowing in sunli...",13
3,Tomato healthy,"A clean and healthy tomato leaf image, perfect...",13
4,Tomato Late blight,A tomato leaf showing dark brown lesions and w...,7
...,...,...,...
82547,Tomato Spider mites Two spotted spider mite,An image of a tomato leaf displaying symptoms ...,10
82548,Tomato Septoria leaf spot,"A tomato leaf showing small, circular brown sp...",9
82549,Tomato Septoria leaf spot,A tomato plant leaf infected with Septoria lyc...,9
82550,Tomato Septoria leaf spot,A tomato leaf outdoors with visible signs of S...,9
82551,Tomato Septoria leaf spot,A dataset image of a tomato leaf showing sympt...,9

In [ ]:
df_train, df_test = train_test_split(df, train_size=0.8)

In [ ]:
from datasets import Dataset

In [ ]:
train_dataset = Dataset.from_pandas(df_train)
test_dataset = Dataset.from_pandas(df_test)

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)

In [ ]:
from transformers import AutoTokenizer

In [ ]:
model_name = "distilbert-base-uncased"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
def mapper_function(data):
  return tokenizer(data['captions'],truncation=True)

In [ ]:
tokenized_train = train_dataset.map(mapper_function, batched = True)
tokenized_train = test_dataset.map(mapper_function, batched = True)

Map:   0%|          | 0/66041 [00:00<?, ? examples/s]

Map:   0%|          | 0/16511 [00:00<?, ? examples/s]

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(model_name,num_labels=15)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.35.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.19.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.12.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 449.4 kB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
from transformers import Trainer, TrainingArguments
from transformers import DataCollator
import evaluate
import numpy as np

In [ ]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [ ]:
eval_metric = evaluate.load("accuracy")

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics(pred):
  logits,labels = pred
  prediction = np.argmax(logits,axis=1)
  return eval_metric.compute(prediction,labels)

In [ ]:
from transformers import Trainer, TrainingArguments

training_arguments = TrainingArguments(
    output_dir="checkpoints",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=1e-4,
    num_train_epochs=3,  # corrected
    weight_decay=0.01,
    logging_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    report_to="none",
)

In [ ]:
# 1. Define a tokenization function
def tokenize_function(examples):
    return tokenizer(examples["caption"], padding="max_length", truncation=True)

# 2. Apply it to train and test datasets
tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_test = test_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/66041 [00:00<?, ? examples/s]

Map:   0%|          | 0/16511 [00:00<?, ? examples/s]

In [ ]:
trainer = Trainer(
    model=model,
    args=training_arguments,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

/tmp/ipython-input-3266090949.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=12384, training_loss=0.004263064463518184, metrics={'train_runtime': 8804.2365, 'train_samples_per_second': 22.503, 'train_steps_per_second': 1.407, 'total_flos': 2.625092293658112e+16, 'train_loss': 0.004263064463518184, 'epoch': 3.0})

In [ ]:
# Save the model and tokenizer to a folder called 'saved_model'
trainer.save_model("saved_model")
tokenizer.save_pretrained("saved_model")

('saved_model/tokenizer_config.json',
 'saved_model/special_tokens_map.json',
 'saved_model/vocab.txt',
 'saved_model/added_tokens.json',
 'saved_model/tokenizer.json')

In [ ]:
trainer.save_model("/content/drive/MyDrive/saved_model")
tokenizer.save_pretrained("/content/drive/MyDrive/saved_model")

('/content/drive/MyDrive/saved_model/tokenizer_config.json',
 '/content/drive/MyDrive/saved_model/special_tokens_map.json',
 '/content/drive/MyDrive/saved_model/vocab.txt',
 '/content/drive/MyDrive/saved_model/added_tokens.json',
 '/content/drive/MyDrive/saved_model/tokenizer.json')

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "saved_model"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

In [ ]:
text = ["This is a sample caption."]
inputs = tokenizer(text, truncation=True, padding=True, return_tensors="pt")
outputs = model(**inputs)
predictions = outputs.logits.argmax(dim=1)
print("Predicted label:", predictions.item())

Predicted label: 13

In [ ]:
import pandas as pd
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer


df = pd.read_parquet("hf://datasets/ButterChicken98/plantvillage-image-text-pairs/data/train-00000-of-00001.parquet")

print(df.columns)
print(df.head())
class_column_name = 'caption'
class_names = df[class_column_name].unique().tolist()
print("Class names extracted:")
print(class_names)
model_path = "saved_model"
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
def predict(text):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
        predicted_idx = torch.argmax(outputs.logits, dim=1).item()
    return class_names[predicted_idx]
sample_text = "image of a healthy plant leaf"
prediction = predict(sample_text)
print(f"Predicted class: {prediction}")

Index(['image', 'caption', 'captions'], dtype='object')
                                               image              caption  \
0  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...       Tomato healthy
1  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...   Tomato Late blight
2  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...       Tomato healthy
3  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...  Tomato mosaic virus
4  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...  Pepper bell healthy

                                            captions
0  [A vibrant green and healthy tomato leaf with ...
1  [A tomato leaf showing dark brown lesions and ...
2  [A vibrant green and healthy tomato leaf with ...
3  [A tomato leaf with mosaic-like patterns of li...
4  [A fresh green bell pepper leaf with a smooth,...
Class names extracted:
['Tomato healthy', 'Tomato Late blight', 'Tomato mosaic virus', 'Pepper bell healthy', 'Potato Early blight', 'Tomato Early blight', 'Tomato YellowLeaf Curl Virus', 'Tomato Target Spot', 'Pepper bell Bacterial spot', 'Tomato Septoria leaf spot', 'Tomato Spider mites Two spotted spider mite', 'Tomato Bacterial spot', 'Potato Late blight', 'Tomato Leaf Mold', 'Potato healthy']
Predicted class: Tomato Leaf Mold

In [ ]:
!zip -r saved_model.zip saved_model

  adding: saved_model/ (stored 0%)
  adding: saved_model/model.safetensors (deflated 8%)
  adding: saved_model/training_args.bin (deflated 53%)
  adding: saved_model/tokenizer_config.json (deflated 75%)
  adding: saved_model/config.json (deflated 59%)
  adding: saved_model/special_tokens_map.json (deflated 42%)
  adding: saved_model/tokenizer.json (deflated 71%)
  adding: saved_model/vocab.txt (deflated 53%)

In [ ]:
import joblib

joblib.dump(encoder, "label_encoder.pkl")

['label_encoder.pkl']

In [ ]:
import joblib

encoder = joblib.load("label_encoder.pkl")
text_class_names = encoder.classes_.tolist()